- name: to print the statements
  hosts: localhost
  vars_files: variables.yaml
  tasks:
  - name: wishing
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}, Trainer is {{name}} Duration is {{Duration}} month"